library(testthat)
library(ribModel)

context("Sequence Summary")

ss <- new(SequenceSummary, 
"ATGCTCATTCTCACTGCTGCCTCGTAG"
)

test_that("AA counts for AA", {
	expect_equal(ss$getAACountForAA("M"), 1)
	expect_equal(ss$getAACountForAA("L"), 2)
	expect_equal(ss$getAACountForAA("I"), 1)
	expect_equal(ss$getAACountForAA("T"), 1)
	expect_equal(ss$getAACountForAA("A"), 2)
	expect_equal(ss$getAACountForAA("S"), 1)
	expect_equal(ss$getAACountForAA("X"), 1)
	expect_equal(ss$getAACountForAA("G"), 0)
})

test_that("AA counts for AA Index", {
  expect_equal(ss$getAACountForAAIndex(10), 1)
  expect_equal(ss$getAACountForAAIndex(9), 2)
  expect_equal(ss$getAACountForAAIndex(7), 1)
  expect_equal(ss$getAACountForAAIndex(16), 1)
  expect_equal(ss$getAACountForAAIndex(0), 2)
  expect_equal(ss$getAACountForAAIndex(15), 1)
  expect_equal(ss$getAACountForAAIndex(21), 1)
  expect_equal(ss$getAACountForAAIndex(2), 0)
})

test_that("Codon Counts for Codon", {
  expect_equal(ss$getCodonCountForCodon("ATG"), 1)
  expect_equal(ss$getCodonCountForCodon("CTC"), 2)
  expect_equal(ss$getCodonCountForCodon("ATT"), 1)
  expect_equal(ss$getCodonCountForCodon("ACT"), 1)
  expect_equal(ss$getCodonCountForCodon("GCT"), 1)
  expect_equal(ss$getCodonCountForCodon("GCC"), 1)
  expect_equal(ss$getCodonCountForCodon("TCG"), 1)
  expect_equal(ss$getCodonCountForCodon("TAG"), 1)
  expect_equal(ss$getCodonCountForCodon("AAA"), 0)
})

test_that("Codon Counts for Codon Index", {
  expect_equal(ss$getCodonCountForCodonIndex(29), 1)
  expect_equal(ss$getCodonCountForCodonIndex(24), 2)
  expect_equal(ss$getCodonCountForCodonIndex(20), 1)
  expect_equal(ss$getCodonCountForCodonIndex(51), 1)
  expect_equal(ss$getCodonCountForCodonIndex(3), 1)
  expect_equal(ss$getCodonCountForCodonIndex(1), 1)
  expect_equal(ss$getCodonCountForCodonIndex(46), 1)
  expect_equal(ss$getCodonCountForCodonIndex(62), 1)
  expect_equal(ss$getCodonCountForCodonIndex(2), 0)
})

test_that("RFP Observed test", {
  ss$setRFPObserved(0, 45)
  ss$setRFPObserved(1, 52)
  ss$setRFPObserved(2, 63)
  ss$setRFPObserved(60, 23)
  expect_equal(ss$getRFPObserved(0), 45)
  expect_equal(ss$getRFPObserved(1), 52)
  expect_equal(ss$getRFPObserved(2), 63)
  expect_equal(ss$getRFPObserved(60), 23)
})

test_that("Codon Positions", {
  # TODO: These return vectors. Fix it.
  expect_equal(ss$getCodonPositions(29), c(0))
  expect_equal(ss$getCodonPositions(24), c(1,3))
  expect_equal(ss$getCodonPositions(20), c(2))
  expect_equal(ss$getCodonPositions(51), c(4))
  expect_equal(ss$getCodonPositions(3), c(5))
  expect_equal(ss$getCodonPositions(1), c(6))
  expect_equal(ss$getCodonPositions(46), c(7))
  expect_equal(ss$getCodonPositions(62), c(8))
  expect_equal(ss$getCodonPositions(54), numeric(0))
})

test_that("Clear", {
  ss$clear()
  
  # i-1 is because of the difference in indexing from R to C++
  
  for (i in 1:64) {
    expect_equal(ss$getCodonCountForCodonIndex(i-1), 0)
    expect_equal(ss$getRFPObserved(i-1), 0)
  }
  
  for (i in 1:22) {
    expect_equal(ss$getAACountForAAIndex(i-1), 0)
  }
})

ss$processSequence("ATGCTCATTCTCACTGCTGCCTCGTAG")

test_that("Process Sequence", {
  
  expect_equal(ss$getAACountForAA("I"), 1)
  expect_equal(ss$getAACountForAA("T"), 1)
  expect_equal(ss$getAACountForAAIndex(15), 1)
  expect_equal(ss$getAACountForAAIndex(21), 1)
  expect_equal(ss$getCodonCountForCodon("ATT"), 1)
  expect_equal(ss$getCodonCountForCodon("ACT"), 1)
  expect_equal(ss$getCodonCountForCodon("GCT"), 1)
  expect_equal(ss$getCodonCountForCodon("GCC"), 1)
  expect_equal(ss$getCodonPositions(24), c(1,3))
  expect_equal(ss$getCodonPositions(20), c(2))
})

test_that("AA to AA index", {
  expect_equal(AAToAAIndex("A"), 0)
  expect_equal(AAToAAIndex("C"), 1)
  expect_equal(AAToAAIndex("D"), 2)
  expect_equal(AAToAAIndex("E"), 3)
  expect_equal(AAToAAIndex("F"), 4)
  expect_equal(AAToAAIndex("G"), 5)
  expect_equal(AAToAAIndex("H"), 6)
  expect_equal(AAToAAIndex("I"), 7)
  expect_equal(AAToAAIndex("K"), 8)
  expect_equal(AAToAAIndex("L"), 9)
  expect_equal(AAToAAIndex("M"), 10)
  expect_equal(AAToAAIndex("N"), 11)
  expect_equal(AAToAAIndex("P"), 12)
  expect_equal(AAToAAIndex("Q"), 13)
  expect_equal(AAToAAIndex("R"), 14)
  expect_equal(AAToAAIndex("S"), 15)
  expect_equal(AAToAAIndex("T"), 16)
  expect_equal(AAToAAIndex("V"), 17)
  expect_equal(AAToAAIndex("W"), 18)
  expect_equal(AAToAAIndex("Y"), 19)
  expect_equal(AAToAAIndex("Z"), 20)
  expect_equal(AAToAAIndex("X"), 21)
})

test_that("AA Index to Codon Range", {
  expect_equal(AAIndexToCodonRange(0, FALSE), c(0,4))
  expect_equal(AAIndexToCodonRange(1, FALSE), c(4,6))
  expect_equal(AAIndexToCodonRange(2, FALSE), c(6,8))
  expect_equal(AAIndexToCodonRange(3, FALSE), c(8,10))
  expect_equal(AAIndexToCodonRange(4, FALSE), c(10,12))
  expect_equal(AAIndexToCodonRange(5, FALSE), c(12,16))
  expect_equal(AAIndexToCodonRange(6, FALSE), c(16,18))
  expect_equal(AAIndexToCodonRange(7, FALSE), c(18,21))
  expect_equal(AAIndexToCodonRange(8, FALSE), c(21,23))
  expect_equal(AAIndexToCodonRange(9, FALSE), c(23,29))
  expect_equal(AAIndexToCodonRange(10, FALSE), c(29,30))
  expect_equal(AAIndexToCodonRange(11, FALSE), c(30,32))
  expect_equal(AAIndexToCodonRange(12, FALSE), c(32,36))
  expect_equal(AAIndexToCodonRange(13, FALSE), c(36,38))
  expect_equal(AAIndexToCodonRange(14, FALSE), c(38,44))
  expect_equal(AAIndexToCodonRange(15, FALSE), c(44,48))
  expect_equal(AAIndexToCodonRange(16, FALSE), c(48,52))
  expect_equal(AAIndexToCodonRange(17, FALSE), c(52,56))
  expect_equal(AAIndexToCodonRange(18, FALSE), c(56,57))
  expect_equal(AAIndexToCodonRange(19, FALSE), c(57,59))
  expect_equal(AAIndexToCodonRange(20, FALSE), c(59,61))
  expect_equal(AAIndexToCodonRange(21, FALSE), c(61,64))
  expect_equal(AAIndexToCodonRange(0, TRUE), c(0,3))
  expect_equal(AAIndexToCodonRange(1, TRUE), c(3,4))
  expect_equal(AAIndexToCodonRange(2, TRUE), c(4,5))
  expect_equal(AAIndexToCodonRange(3, TRUE), c(5,6))
  expect_equal(AAIndexToCodonRange(4, TRUE), c(6,7))
  expect_equal(AAIndexToCodonRange(5, TRUE), c(7,10))
  expect_equal(AAIndexToCodonRange(6, TRUE), c(10,11))
  expect_equal(AAIndexToCodonRange(7, TRUE), c(11,13))
  expect_equal(AAIndexToCodonRange(8, TRUE), c(13,14))
  expect_equal(AAIndexToCodonRange(9, TRUE), c(14,19))
  expect_equal(AAIndexToCodonRange(10, TRUE), c(19,19))
  expect_equal(AAIndexToCodonRange(11, TRUE), c(19,20))
  expect_equal(AAIndexToCodonRange(12, TRUE), c(20,23))
  expect_equal(AAIndexToCodonRange(13, TRUE), c(23,24))
  expect_equal(AAIndexToCodonRange(14, TRUE), c(24,29))
  expect_equal(AAIndexToCodonRange(15, TRUE), c(29,32))
  expect_equal(AAIndexToCodonRange(16, TRUE), c(32,35))
  expect_equal(AAIndexToCodonRange(17, TRUE), c(35,38))
  expect_equal(AAIndexToCodonRange(18, TRUE), c(38,38))
  expect_equal(AAIndexToCodonRange(19, TRUE), c(38,39))
  expect_equal(AAIndexToCodonRange(20, TRUE), c(39,40))
  expect_equal(AAIndexToCodonRange(21, TRUE), c(40,40))
  expect_equal(AAIndexToCodonRange(22, FALSE), c(0,0))
})

test_that("AA To Codon Range", {
  expect_equal(AAToCodonRange("A", FALSE), c(0,4))
  expect_equal(AAToCodonRange("C", FALSE), c(4,6))
  expect_equal(AAToCodonRange("D", FALSE), c(6,8))
  expect_equal(AAToCodonRange("E", FALSE), c(8,10))
  expect_equal(AAToCodonRange("F", FALSE), c(10,12))
  expect_equal(AAToCodonRange("G", FALSE), c(12,16))
  expect_equal(AAToCodonRange("H", FALSE), c(16,18))
  expect_equal(AAToCodonRange("I", FALSE), c(18,21))
  expect_equal(AAToCodonRange("K", FALSE), c(21,23))
  expect_equal(AAToCodonRange("L", FALSE), c(23,29))
  expect_equal(AAToCodonRange("M", FALSE), c(29,30))
  expect_equal(AAToCodonRange("N", FALSE), c(30,32))
  expect_equal(AAToCodonRange("P", FALSE), c(32,36))
  expect_equal(AAToCodonRange("Q", FALSE), c(36,38))
  expect_equal(AAToCodonRange("R", FALSE), c(38,44))
  expect_equal(AAToCodonRange("S", FALSE), c(44,48))
  expect_equal(AAToCodonRange("T", FALSE), c(48,52))
  expect_equal(AAToCodonRange("V", FALSE), c(52,56))
  expect_equal(AAToCodonRange("W", FALSE), c(56,57))
  expect_equal(AAToCodonRange("Y", FALSE), c(57,59))
  expect_equal(AAToCodonRange("Z", FALSE), c(59,61))
  expect_equal(AAToCodonRange("X", FALSE), c(61,64))
  expect_equal(AAToCodonRange("A", TRUE), c(0,3))
  expect_equal(AAToCodonRange("C", TRUE), c(3,4))
  expect_equal(AAToCodonRange("D", TRUE), c(4,5))
  expect_equal(AAToCodonRange("E", TRUE), c(5,6))
  expect_equal(AAToCodonRange("F", TRUE), c(6,7))
  expect_equal(AAToCodonRange("G", TRUE), c(7,10))
  expect_equal(AAToCodonRange("H", TRUE), c(10,11))
  expect_equal(AAToCodonRange("I", TRUE), c(11,13))
  expect_equal(AAToCodonRange("K", TRUE), c(13,14))
  expect_equal(AAToCodonRange("L", TRUE), c(14,19))
  expect_equal(AAToCodonRange("M", TRUE), c(19,19))
  expect_equal(AAToCodonRange("N", TRUE), c(19,20))
  expect_equal(AAToCodonRange("P", TRUE), c(20,23))
  expect_equal(AAToCodonRange("Q", TRUE), c(23,24))
  expect_equal(AAToCodonRange("R", TRUE), c(24,29))
  expect_equal(AAToCodonRange("S", TRUE), c(29,32))
  expect_equal(AAToCodonRange("T", TRUE), c(32,35))
  expect_equal(AAToCodonRange("V", TRUE), c(35,38))
  expect_equal(AAToCodonRange("W", TRUE), c(38,38))
  expect_equal(AAToCodonRange("Y", TRUE), c(38,39))
  expect_equal(AAToCodonRange("Z", TRUE), c(39,40))
  expect_equal(AAToCodonRange("X", TRUE), c(40,40))
  expect_equal(AAToCodonRange("B", FALSE), c(0,0))
})